import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Lato } from "next/font/google";
import "@/assets/styles/global.css";
import Menu from "@/components/menu/Menu";
import AuthProvider from "@/components/providers/AuthProvider";
import { UserProvider } from "@/contexts/UserContext";
import Timeline from "@/components/footer/Timeline";
import { PokemonProvider } from "@/contexts/PokemonContext";
import { BattleProvider } from "@/contexts/BattleContext";
import { MapProvider } from "./map/MapContext";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });
const lato = Lato({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <AuthProvider>
          <UserProvider>
            <PokemonProvider>
              <BattleProvider>
                <Menu />
                <MapProvider>
                  <Suspense>{children}</Suspense>
                </MapProvider>
                <Timeline />
              </BattleProvider>
            </PokemonProvider>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
